version: 0.0
Resources:
  TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: "My_todo_task_definition_Frontend"
      LoadBalancerInfo:
        ContainerName: "react"
        ContainerPort: 3000