version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s0z9h6z8
  build:
    commands:
      - docker build -t my_todo_frontend:latest ./frontend/
      - docker tag my_todo_frontend:latest public.ecr.aws/s0z9h6z8/my_todo_frontend:latest
  post_build:
    commands:
      - docker push public.ecr.aws/s0z9h6z8/my_todo_frontend:latest
      - printf '[{"name":"react","imageUri":"%s"}]' public.ecr.aws/s0z9h6z8/my_todo_frontend:latest > imagedefinitions.json
      - aws ecs describe-task-definition --task-definition My_todo_task_definition_Frontend --region us-east-1 | jq .taskDefinition > taskdef.json
artifacts:
  files: 
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json