version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s0z9h6z8
  build:
    commands:
      - docker build -t my_todo_frontend:latest ./frontend/
      - docker tag my_todo_frontend:latest public.ecr.aws/s0z9h6z8/my_todo_frontend:latest
    commands:
      - docker push public.ecr.aws/s0z9h6z8/my_todo_frontend:latest
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetailFrontend.json
artifacts:
  files: 
    - 'image*.json'
    - 'appspec.yaml'
    - 'taskdef.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetailFrontend.json